name=TeensyTFT
version=0.0.1
author=PowerBroker2 <gitstuff2@gmail.com>
maintainer=PowerBroker2 <gitstuff2@gmail.com>
sentence=Teensy wrapper library for super efficient ILI9341-based TFT driving
paragraph=Teensy wrapper library for super efficient ILI9341-based TFT driving
category=Display
url=https://github.com/PowerBroker2/TeensyTFT
architectures=*
